apiVersion: mcserverhosting.net/v2
kind: BungeeDeployment
metadata:
  name: example-bungeedeployment
spec:
  config:
     memory:
      # config.memory.initial -- initial memory for the minecraft server. memory must end in G or M. 
      initial: 500M
      # config.memory.max -- max memory for the minecraft server. memory must end in G or M. 
      max: 1G
     network:
      # config.network.domainName -- The DNS name your players will connect by
      domainName: bungee.mcserverhosting.red
      # config.network.routeName -- The DNS name that will route to your node's IP address.
      routeName: bungee.mcserverhosting.red
  groupID: 1000
  jar: https://firebasestorage.googleapis.com/v0/b/mchostingnet-202204.appspot.com/o/FlameCord.jar?alt=media&token=9a8ba3db-7847-4d62-9a7f-10f65fe54601
  online: true
  #true for on, false for off
  type: CUSTOM
  userID: 1001
