apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: restrictions.deployments.mcserverhosting.net
spec:
  group: deployments.mcserverhosting.net
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: restrictions
    singular: restriction
    kind: Restriction
    shortNames:
    - restriction
    - res
    - restrictions