kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mcsh-operator
subjects:
- kind: ServiceAccount
  name: mcsh-operator
  namespace: mcsh
roleRef:
  kind: ClusterRole
  name: mcsh-operator
  apiGroup: rbac.authorization.k8s.io
