apiVersion: mcserverhosting.net/v2
kind: BungeeDeployment
metadata:
  name: example-bungeedeployment
spec:
  # Default values copied from <project_dir>\helm-charts\bungee-deployment\values.yaml
  
  config:
    memory:
      initial: 500M
      max: 1G
    network:
      domainName: bungee.mcserverhosting.red
      routeName: bungee.mcserverhosting.red
  jar: https://firebasestorage.googleapis.com/v0/b/mchostingnet-202204.appspot.com/o/FlameCord.jar?alt=media&token=9a8ba3db-7847-4d62-9a7f-10f65fe54601
  jarName: FlameCord.jar
  online: true
  plugins:
  - https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/jar/target/ViaVersion-2.2.3.jar
  - https://ci.viaversion.com/job/ViaVersion-Abstraction/lastSuccessfulBuild/artifact/jar/target/ViaVersion-3.0.0-SNAPSHOT.jar
  - https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/lastSuccessfulBuild/artifact/all/target/viabackwards-all-2.4.0-SNAPSHOT.jar
  - https://ci.viaversion.com/view/ViaRewind/job/ViaRewind-DEV/lastSuccessfulBuild/artifact/all/target/viarewind-all-1.5.0-SNAPSHOT.jar
  
